### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by joeyave** [KrystianD/screentool#1]

**Comment by KrystianD** [comment]
It all depends on what distro and window manager you use. When it comes to installation itself, just clone the repo and run `go build` if you have Go SDK installed. You will get an executable file that you can just run. When it comes to running it, it is best to assign it to a hotkey. If you use Ubuntu, [this guide](https://help.ubuntu.com/stable/ubuntu-help/keyboard-shortcuts-set.html.en) may be helpful.

**Comment by KrystianD** [comment]
@joeyave added more build information, also added a precompiled release -> https://github.com/KrystianD/screentool/releases/tag/v1.0

**Comment by joeyave** [comment]
Nice! I've successfully compiled it. Thank you.
