### ISSUE TITLE
screen should be freezed when taking the screenshot

### ISSUE THREAD

**Issue by joeyave** [KrystianD/screentool#2]
Imagine you want to take a screenshot of a live video that can't be paused. It would be nice to "pause" everything on the screen when you are taking the screen.

**Comment by KrystianD** [comment]
Yes, I was thinking about such feature, would also be helpful for making screenshots of popups that would go away when you click other window. Basically, it would capture the whole screen on run and allow user to select the range/window.

**Comment by KrystianD** [comment]
@joeyave, feature implemented. You can add `--freeze` command line option to take a screenshot immediately after starting the tool. All other experience (selecting region/window, annotations) remains unchanged.

**Comment by joeyave** [comment]
Thanks, will check it out!
