### ISSUE TITLE
window's capture doesn't work when fractional scale is enabled (ubuntu 20.10)

### ISSUE THREAD

**Issue by joeyave** [KrystianD/screentool#3]

**Comment by KrystianD** [comment]
Okay, I will check it out.

**Comment by KrystianD** [comment]
@joeyave could you please check now? I was not able to reproduce issue with fractional scaling (as it was not possible to set on VM) but there indeed was a problem with detecting windows' geometry (when decorations are enabled) which has been fixed.

**Comment by joeyave** [comment]
@KrystianD I'll try it out. By the way, fractional scaling is only available with Ubuntu 20.10. Forgot to mention.

**Comment by joeyave** [comment]
Doesn't seem to solve the issue. I've tried to record a screen with Kazam to show you the behavior but it appeared that Kazam has the same issue! I've found a [bug report](https://bugs.launchpad.net/ubuntu/+bug/1283424) where someone seems to mention how to fix that, maybe it'll help.

**Comment by joeyave** [comment]
The same happens (image crops) when I make a screenshot with an arrow. For example, the first image is done without an arrow and the second is done in the same area with an arrow (pressing Shift key). 

First:
![image](https://user-images.githubusercontent.com/48005710/99251674-64c5ac80-2816-11eb-9d28-5b041461ca5f.png)

Second (see how it cropped Projects and Milestone part of the original image):
![image](https://user-images.githubusercontent.com/48005710/99251693-74dd8c00-2816-11eb-9aa2-f38b447312d9.png)

**Comment by KrystianD** [comment]
@joeyave, finally, I managed to reproduce and fix the issue. Could you please check now?

**Comment by joeyave** [comment]
@KrystianD it works great now! Thank you.

**Comment by joeyave** [comment]
Oh, noticed that full screen screenshot with status bar doesn't work as expected.

![image](https://user-images.githubusercontent.com/48005710/100066940-5131cb80-2e3e-11eb-990a-8b8260f351c8.png)

Full screen capture without status bar does the job well.

**Comment by KrystianD** [comment]
Okay, should be fixed.
